// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: payment.proto

package payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bank transfer method
type PaymentData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderCode       string                 `protobuf:"bytes,2,opt,name=order_code,json=orderCode,proto3" json:"order_code,omitempty"`
	UserId          string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount          float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Provider        string                 `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	ProviderDetails string                 `protobuf:"bytes,6,opt,name=provider_details,json=providerDetails,proto3" json:"provider_details,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PaymentData) Reset() {
	*x = PaymentData{}
	mi := &file_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentData) ProtoMessage() {}

func (x *PaymentData) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentData.ProtoReflect.Descriptor instead.
func (*PaymentData) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentData) GetOrderCode() string {
	if x != nil {
		return x.OrderCode
	}
	return ""
}

func (x *PaymentData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PaymentData) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentData) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *PaymentData) GetProviderDetails() string {
	if x != nil {
		return x.ProviderDetails
	}
	return ""
}

func (x *PaymentData) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ProcessPaymentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrderCode       string                 `protobuf:"bytes,1,opt,name=order_code,json=orderCode,proto3" json:"order_code,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount          float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Provider        string                 `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	ProviderDetails string                 `protobuf:"bytes,5,opt,name=provider_details,json=providerDetails,proto3" json:"provider_details,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProcessPaymentRequest) Reset() {
	*x = ProcessPaymentRequest{}
	mi := &file_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentRequest) ProtoMessage() {}

func (x *ProcessPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentRequest.ProtoReflect.Descriptor instead.
func (*ProcessPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessPaymentRequest) GetOrderCode() string {
	if x != nil {
		return x.OrderCode
	}
	return ""
}

func (x *ProcessPaymentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProcessPaymentRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ProcessPaymentRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ProcessPaymentRequest) GetProviderDetails() string {
	if x != nil {
		return x.ProviderDetails
	}
	return ""
}

func (x *ProcessPaymentRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ProcessPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *PaymentData           `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	PaymentUrl    string                 `protobuf:"bytes,2,opt,name=payment_url,json=paymentUrl,proto3" json:"payment_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentResponse) Reset() {
	*x = ProcessPaymentResponse{}
	mi := &file_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentResponse) ProtoMessage() {}

func (x *ProcessPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentResponse.ProtoReflect.Descriptor instead.
func (*ProcessPaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessPaymentResponse) GetPayment() *PaymentData {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *ProcessPaymentResponse) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

type CancelPaymentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to PaymentIdentifier:
	//
	//	*CancelPaymentRequest_PaymentId
	//	*CancelPaymentRequest_OrderCode
	PaymentIdentifier isCancelPaymentRequest_PaymentIdentifier `protobuf_oneof:"payment_identifier"`
	Reason            string                                   `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CancelPaymentRequest) Reset() {
	*x = CancelPaymentRequest{}
	mi := &file_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPaymentRequest) ProtoMessage() {}

func (x *CancelPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPaymentRequest.ProtoReflect.Descriptor instead.
func (*CancelPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{3}
}

func (x *CancelPaymentRequest) GetPaymentIdentifier() isCancelPaymentRequest_PaymentIdentifier {
	if x != nil {
		return x.PaymentIdentifier
	}
	return nil
}

func (x *CancelPaymentRequest) GetPaymentId() string {
	if x != nil {
		if x, ok := x.PaymentIdentifier.(*CancelPaymentRequest_PaymentId); ok {
			return x.PaymentId
		}
	}
	return ""
}

func (x *CancelPaymentRequest) GetOrderCode() string {
	if x != nil {
		if x, ok := x.PaymentIdentifier.(*CancelPaymentRequest_OrderCode); ok {
			return x.OrderCode
		}
	}
	return ""
}

func (x *CancelPaymentRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type isCancelPaymentRequest_PaymentIdentifier interface {
	isCancelPaymentRequest_PaymentIdentifier()
}

type CancelPaymentRequest_PaymentId struct {
	PaymentId string `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3,oneof"`
}

type CancelPaymentRequest_OrderCode struct {
	OrderCode string `protobuf:"bytes,2,opt,name=order_code,json=orderCode,proto3,oneof"`
}

func (*CancelPaymentRequest_PaymentId) isCancelPaymentRequest_PaymentIdentifier() {}

func (*CancelPaymentRequest_OrderCode) isCancelPaymentRequest_PaymentIdentifier() {}

var File_payment_proto protoreflect.FileDescriptor

const file_payment_proto_rawDesc = "" +
	"\n" +
	"\rpayment.proto\x12\apayment\x1a\x1bgoogle/protobuf/empty.proto\"\xb1\x02\n" +
	"\vPaymentData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"order_code\x18\x02 \x01(\tR\torderCode\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bprovider\x18\x05 \x01(\tR\bprovider\x12)\n" +
	"\x10provider_details\x18\x06 \x01(\tR\x0fproviderDetails\x12>\n" +
	"\bmetadata\x18\a \x03(\v2\".payment.PaymentData.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb5\x02\n" +
	"\x15ProcessPaymentRequest\x12\x1d\n" +
	"\n" +
	"order_code\x18\x01 \x01(\tR\torderCode\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x12)\n" +
	"\x10provider_details\x18\x05 \x01(\tR\x0fproviderDetails\x12H\n" +
	"\bmetadata\x18\x06 \x03(\v2,.payment.ProcessPaymentRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"i\n" +
	"\x16ProcessPaymentResponse\x12.\n" +
	"\apayment\x18\x01 \x01(\v2\x14.payment.PaymentDataR\apayment\x12\x1f\n" +
	"\vpayment_url\x18\x02 \x01(\tR\n" +
	"paymentUrl\"\x86\x01\n" +
	"\x14CancelPaymentRequest\x12\x1f\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tH\x00R\tpaymentId\x12\x1f\n" +
	"\n" +
	"order_code\x18\x02 \x01(\tH\x00R\torderCode\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reasonB\x14\n" +
	"\x12payment_identifier2\xaf\x01\n" +
	"\x0ePaymentService\x12S\n" +
	"\x0eProcessPayment\x12\x1e.payment.ProcessPaymentRequest\x1a\x1f.payment.ProcessPaymentResponse\"\x00\x12H\n" +
	"\rCancelPayment\x12\x1d.payment.CancelPaymentRequest\x1a\x16.google.protobuf.Empty\"\x00BKZIgithub.com/vogiaan1904/e-commerce-grpc-nest-proto/protogen/golang/paymentb\x06proto3"

var (
	file_payment_proto_rawDescOnce sync.Once
	file_payment_proto_rawDescData []byte
)

func file_payment_proto_rawDescGZIP() []byte {
	file_payment_proto_rawDescOnce.Do(func() {
		file_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)))
	})
	return file_payment_proto_rawDescData
}

var file_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_payment_proto_goTypes = []any{
	(*PaymentData)(nil),            // 0: payment.PaymentData
	(*ProcessPaymentRequest)(nil),  // 1: payment.ProcessPaymentRequest
	(*ProcessPaymentResponse)(nil), // 2: payment.ProcessPaymentResponse
	(*CancelPaymentRequest)(nil),   // 3: payment.CancelPaymentRequest
	nil,                            // 4: payment.PaymentData.MetadataEntry
	nil,                            // 5: payment.ProcessPaymentRequest.MetadataEntry
	(*emptypb.Empty)(nil),          // 6: google.protobuf.Empty
}
var file_payment_proto_depIdxs = []int32{
	4, // 0: payment.PaymentData.metadata:type_name -> payment.PaymentData.MetadataEntry
	5, // 1: payment.ProcessPaymentRequest.metadata:type_name -> payment.ProcessPaymentRequest.MetadataEntry
	0, // 2: payment.ProcessPaymentResponse.payment:type_name -> payment.PaymentData
	1, // 3: payment.PaymentService.ProcessPayment:input_type -> payment.ProcessPaymentRequest
	3, // 4: payment.PaymentService.CancelPayment:input_type -> payment.CancelPaymentRequest
	2, // 5: payment.PaymentService.ProcessPayment:output_type -> payment.ProcessPaymentResponse
	6, // 6: payment.PaymentService.CancelPayment:output_type -> google.protobuf.Empty
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_payment_proto_init() }
func file_payment_proto_init() {
	if File_payment_proto != nil {
		return
	}
	file_payment_proto_msgTypes[3].OneofWrappers = []any{
		(*CancelPaymentRequest_PaymentId)(nil),
		(*CancelPaymentRequest_OrderCode)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_proto_goTypes,
		DependencyIndexes: file_payment_proto_depIdxs,
		MessageInfos:      file_payment_proto_msgTypes,
	}.Build()
	File_payment_proto = out.File
	file_payment_proto_goTypes = nil
	file_payment_proto_depIdxs = nil
}
